Algoritmo "conversaotemperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/03/2021
Var
// Seção de Declarações das variáveis 
c,f: real

Inicio

escreval("Digite a temperatura em ºF: ")
leia(f)

c <- (5 * (f-32) / 9)

escreval("A temperatura em ºC é: ", c)

Fimalgoritmo